### ISSUE TITLE
Fail reading the list of available Look&Feel packages

### ISSUE THREAD

**Issue by alxlg** [daehruoydeef/Yin-Yang#10]
This is the output of `lookandfeeltool -l`:

```
it.alexl.breezeplus
it.alexl.breezeplusdark
org.kde.breeze.desktop
org.kde.breezedark.desktop
```

But this is what the setting show:
![immagine](https://user-images.githubusercontent.com/26327475/54624531-d65fbd00-4a6d-11e9-8ad4-ecebf8304e0e.png)

So it fails to parse the `\n` character but only for the first two lines/themes.

**Comment by daehruoydeef** [comment]
The Problem occurs because the subprocess.check_output() functions returns the lookandfeel -l list in a non formatted way including all the /n /b and several '. I came up with a Regex which  I thought would catch all cases but obiously this is not the case. 

[This is the line of interest](https://github.com/daehruoydeef/Yin-Yang/blob/master/bin/gui.py#L103)

You could help me by providing the output from this python call:
`subprocess.check_output(["lookandfeeltool", "-l"])`
I will try to come up with a better regex to match all cases. 

Or you could try it yourself with your output of the command above (make sure to select python):
[See this website](https://regex101.com/)
with this Regular Expression:
`b]?[']?n?([A-z]*.[A-z]*.[A-z]*-?.[A-z]*.[A-z]*)\\\\`
and your output copied from a print statement inside python3. If your Regex is proven to catch all cases I will immediately update the Code.

**Comment by eogan** [comment]
I have the sae issue here. I don't know how to conduct the tests you asked but grep sounds a bit awkward. Can't the garbage be removed in a more simple way ?
https://stackoverflow.com/questions/36422572/python-subprocess-output-without-n

**Comment by daehruoydeef** [comment]
Thank you for your engagement! I will fix this when I find the time. It will definetly be fixed with Yin-Yang 3.0.

**Comment by eogan** [comment]
I've got a fix:
ugly_themes = subprocess.check_output(["lookandfeeltool", "-l"],universal_newlines=True)
pretty_themes = ugly_themes.splitlines()
I am very new to Python so I don't really know what I do but it works here :-)

**Comment by eogan** [comment]
Bug fixed :)

**Comment by daehruoydeef** [comment]
Wow awesome @eogan for fixing this. I was about to look into this and I am so glad you fixed this I will merge this as soon as possible. Great Work, you will sure earn a place in the Contributors list on the new Readme.
