### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by Optica1** [daehruoydeef/Yin-Yang#13]
Thank a lot for this simple application.
Is it possible to add atom support? I switch between dark and light using the F12 hotkey of the package 'theme-switcher'. It works nice, but having this automated would be even more awesome!
I'd help out if I could, but I have no idea how to get started.

**Comment by daehruoydeef** [comment]
I was just about to write an answer to why it does not work because I already tried to add it. But nevermind, Atom is featured in the next release!

**Comment by Optica1** [comment]
Very nice you've found a solution, I'm looking forward to it.
Many thanks!

**Comment by daehruoydeef** [comment]
@Optica1 hey listen! 
Atom support is in, would be really great if you could test out if it works. Since I am not using Atom as my main Editor I only did testing so it would work for me but cannot tell for sure if this is the case for the minority. 
For example VSCode is not named the same on all Distros, by know I have found 3 diffrent names for the VSCode folder they are:
Code - OSS
Code
Code - Insiders
all of them behave the same. I wonder if Atom also got this weird naming so I was not able to test this throughly. I will close this issue, if you encounter any new Issues please open a new one.
