### ISSUE TITLE
Cannot open Settings on GNOME

### ISSUE THREAD

**Issue by yochananmarqos** [daehruoydeef/Yin-Yang#20]
I just built with dcef1e0 and cannot open Settings on Manjaro GNOME:
```
$ env QT_AUTO_SCREEN_SCALE_FACTOR=1 sh /usr/bin/yin-yang -gui
qt5ct: using qt5ct plugin
0
Traceback (most recent call last):
  File "/opt/yin-yang/src/gui.py", line 223, in openSettings
    self.secwindow = SettingsWindow()
  File "/opt/yin-yang/src/gui.py", line 24, in __init__
    self.syncWithConfig()
  File "/opt/yin-yang/src/gui.py", line 76, in syncWithConfig
    self.getKdeThemes()
  File "/opt/yin-yang/src/gui.py", line 125, in getKdeThemes
    if (config.get("desktop") == "kde"):
  File "/opt/yin-yang/src/config.py", line 146, in get
    return config[key]
KeyError: 'desktop'
/usr/bin/yin-yang: line 2:  1656 Aborted                 (core dumped) python3 /opt/yin-yang/main.py $@

GNOME 3.32.0
python-pyqt5  5.12.1
python-qtpy  1.6.0

**Comment by daehruoydeef** [comment]
Thanks for the bug report, could you please post the output of
echo $GDMSESSION
And the distro you are currently on.
The problem seems to be that every Distro is implementing GDMSESSION differently for example some would set the variable to 'gnome' others would come up with 'gnome-desktop'. I am really thankful that you catched this bug and I will fix this as soon as possible and try to come up with a more general approach.

**Comment by yochananmarqos** [comment]
```
$ echo $GDMSESSION
gnome
```

**Comment by daehruoydeef** [comment]
Thanks for your help, could you please check if the last commit fixed this for you, simply clone the Repository again, run sudo sh install.sh and open the gui to reconfigure Yin-Yang. Fill in your gtk theme and hope for the best. Would be good if you could report back if this works for you so I can close this issue.

**Comment by yochananmarqos** [comment]
I now get a notification, "It looks like you're not running KDE" and Settings does not open:
```
$ env QT_AUTO_SCREEN_SCALE_FACTOR=1 sh /usr/bin/yin-yang -gui
qt5ct: using qt5ct plugin
0
Traceback (most recent call last):
  File "/opt/yin-yang/src/gui.py", line 223, in openSettings
    self.secwindow = SettingsWindow()
  File "/opt/yin-yang/src/gui.py", line 24, in __init__
    self.syncWithConfig()
  File "/opt/yin-yang/src/gui.py", line 106, in syncWithConfig
    self.ui.atom_line_light.setText(config.get("atomLightTheme"))
  File "/opt/yin-yang/src/config.py", line 163, in get
    return config[key]
KeyError: 'atomLightTheme'
/usr/bin/yin-yang: line 2: 30059 Aborted                 (core dumped) python3 /opt/yin-yang/main.py $@
```

**Comment by daehruoydeef** [comment]
I see the problem seems that the config which is located at ~/.config/yin_yang/yin_yang.json seems like it is missing some keys.
Would be a good help if you could post your current config so I can see and guess what went wrong otherwise you should delete your config file and restart Yin-Yang with it's Desktop entry, upon first start it will generate a new config which should include all the necassary fields.

**Comment by yochananmarqos** [comment]
I didn't realize there was a config file. Here's the existing one:

```
{
    "version": "2.0",
    "schedule": false,
    "switchToDark": "20:0",
    "switchToLight": "7:0",
    "running": false,
    "theme": "dark",
    "codeLightTheme": "Default Light+",
    "codeDarkTheme": "Default Dark+",
    "codeEnabled": true,
    "kdeLightTheme": "org.kde.breeze.desktop",
    "kdeDarkTheme": "org.kde.breezedark.desktop",
    "kdeEnabled": true,
    "gtkLightTheme": "",
    "gtkDarkTheme": "",
    "gtkEnabled": false,
    "wallpaperLightTheme": "",
    "wallpaperDarkTheme": "",
    "wallpaperEnabled": false,
    "desktop": "gtk"
}
```
I deleted it, let it recreate it and now I can now open Settings. I'll play around with themes when I have more time.

**Comment by daehruoydeef** [comment]
Hey did everything worked out? If everything works I am going to close the Issue. If you want to update Yin-Yang simply reclone the repository and run the install script again.

**Comment by yochananmarqos** [comment]
I tried changing the GTK theme, but it only changed the Application theme, not the Shell theme. GNOME themes can be changed like the example script I wrote [here](https://github.com/FedeDP/Clight/wiki/DE-Integration).

**Comment by daehruoydeef** [comment]
@yochananmarqos I checked your scripts and it boils down to the same system api I am using. However I dbus is not needed and not recommended to use. In order for Yin-Yang to support Gnome-Shell I would need to add another input field since not all Application themes got a matching Gnome-Shell theme. I think adwaita is one example. I will look forward to support it in Yin-Yang 4.0
