### ISSUE TITLE
.DirIcon is missing in the AppImage

### ISSUE THREAD

**Issue by probonopd** [daehruoydeef/Yin-Yang#52]
Hi, thanks for making an AppImage. However, it is missing the `.DirIcon` file. Please see https://github.com/electron-userland/electron-builder/issues/3988.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2007

**Comment by daehruoydeef** [comment]
There is a new installation procedure since there were many problems due to AppImage packaging. Right now the best way to install this Application is to use the install.sh script. Read the README.md for more information. I will close this since AppImage is not the recommended way anymore for running Yin-Yang.

**Comment by probonopd** [comment]
> There is a new installation procedure since there were many problems due to AppImage packaging. 

Sorry to hear that. Is there anything that I could help with?

**Comment by daehruoydeef** [comment]
If you have any experience with packaging I would be more than grateful to have some help packaging this application for Major Distros and provide a .deb .rpm. I have no experience at all and just used some hacky workarounds at the time.

I had some problems with AppImage in the past and since this tool is manipulating the system I guess it would be a smart move to package this as a system package instead of an AppImage.

**Comment by probonopd** [comment]
Hi @daehruoydeef I know nothing about deb and rpm and I find them way too restrictive (you can't even move applications around on the disk or have multiple versions in parallel), this is why I invented AppImage.

> I had some problems with AppImage in the past

I'm here to help you with those!

**Comment by daehruoydeef** [comment]
Wow ok, so let's make this happen. 
I got hit with some errors I believe to be related to AppImage:
[Loading Pythons libs](https://github.com/daehruoydeef/Yin-Yang/issues/24)
[did not worked at all on plasma 5.16 > ](https://github.com/daehruoydeef/Yin-Yang/issues/27)
[Not using native widget style](https://github.com/daehruoydeef/Yin-Yang/issues/11)

I guess the last error is related to the fact that I tried to package it with the python pyqt version. This resulted in Yin-Yang not knowing about the system status of QT and using it's own version.

I would be really happy to see how a proper AppImage with qt should be build for this Application. 

I remember that I struggled to get a working AppImage version and found it easier to write a installer myself. However this is probably due to the fact that I have a poor understanding of AppImage in general.

**Comment by probonopd** [comment]
* The glibc error comes from building on a too new distribution; please build on the oldest still-supported LTS release, currently xenial

* Never mix Qt parts from inside and outside the AppImage; `/usr/lib64/libKF5QuickAddons.so.5` should NOT be loaded when `libQt5Core.so.5` is inside the AppImage...

* AppImages can only use the styles shipped inside them

**Comment by daehruoydeef** [comment]
> Never mix Qt parts from inside and outside the AppImage; /usr/lib64/libKF5QuickAddons.so.5 should NOT be loaded when libQt5Core.so.5 is inside the AppImage...

I basically used PyInstaller to create a binary file and used that Binary to create the AppImage out of. I did not mixed QT parts inside out by purpose and do not know how to prevent this behavior basically.

> AppImages can only use the styles shipped inside them

Does that mean I dynamically change the theme because i am using a "sandboxed" version of qt?

Can you point me to a AppImage that does use PyQt, I am having a hard time to understand how everything should work together.

**Comment by probonopd** [comment]
Hi @daehruoydeef a very prominent one is the Ultimaker Cura AppImage.

But you don't have to do everything by hand (which can be quite tedious), there are now tools that can greatly simplify the process. Here are two:

* https://github.com/niess/python-appimage by niess
* https://github.com/linuxdeploy/linuxdeploy-plugin-conda by TheAssassin

Please ask in those projects in case the tools are not self-explanatory.

Thanks for making an AppImage!
