### ISSUE TITLE
pip3 not found

### ISSUE THREAD

**Issue by Ryuno-Ki** [daehruoydeef/Yin-Yang#53]
Hey there,

today I tried your program on a new machine (Sabayon Linux).
Want to give you some feedback before I forget.

In install.sh, you're currently assuming `pip3` to be available.
https://github.com/daehruoydeef/Yin-Yang/blob/f7e1d7680ea476802c330d29a7999a2ba63f264d/install.sh#L18-L20

This is not always the case. However, it didn't result in an error message either.

Perhaps it also makes sense to check for a system-wide installed presence first (e.g. via `python -m`) before running this code?

My distribution showed a prompt to install via `pip3 install --user`, but then, the code wouldn't be found.
I went with system-wide installed deps now.

The install.sh ran in either way.

**Comment by daehruoydeef** [comment]
yes you are right the install.sh does assume pip3 to be installed and there are no further checks. There is a note inside the Wiki that you will need python and pip3 to be installed.
I suggest that you stick with the systems package manager installation for pyqt5 since there exist some bugs around the python pyqt5 version.

 I will close this issue since there is a link to the wiki under the installation point that mentions that you will need some dependencies.
