### ISSUE TITLE
[Feature Request] allow for running as daemon

### ISSUE THREAD

**Issue by rubenmantecon** [daehruoydeef/Yin-Yang#77]
Using KDE as main desktgo. Although I have an schedule set, if I poweroff the computer, theme doesn't change, unless I open the app again.

Would be great to run it as startup script, headless

**Comment by l0drex** [comment]
In KDE, you can manually let yin-yang open on start by going to
system settings
→ Startup and Shutdown
→ Autostart

There you can add Yin & Yang as an application. For the headless part:

- edit the properties
-  go to the tab `application`
-  add `-s` in the command section. Now it should look like this:
`env QT_AUTO_SCREEN_SCALE_FACTOR=1 sh /usr/bin/yin-yang -s`

This will start Yin & Yang with the option `scheduled` to run in the background. The names of the sections might be different since I'm using KDE in German.

---
[Some more information about the autostart section](https://userbase.kde.org/System_Settings/Autostart)

**Comment by rubenmantecon** [comment]
Thank you very much! I apologize for opening an issue for something so trivial. My understanding of Bash ans Unix is very limited.

Very appreciated
